-- 자동차 종류가 '세단' 또는 'SUV' 인 자동차 중 2022년 11월 1일부터 2022년 11월 30일까지 대여 가능하고 30일간의 대여 금액이 50만원 이상 200만원 미만
SELECT A.CAR_ID, A.CAR_TYPE, round(A.DAILY_FEE*(100-D.DISCOUNT_RATE)/100*30) as FEE
from CAR_RENTAL_COMPANY_CAR A join CAR_RENTAL_COMPANY_RENTAL_HISTORY H on A.CAR_ID=H.CAR_ID join CAR_RENTAL_COMPANY_DISCOUNT_PLAN D on A.CAR_TYPE=D.CAR_TYPE
where A.CAR_ID not in (select CAR_ID from CAR_RENTAL_COMPANY_RENTAL_HISTORY where START_DATE <= '2022-12-01' and END_DATE>='2022-11-01') 
and D.DURATION_TYPE like '30%'
group by A.CAR_ID
having A.CAR_TYPE in ('세단','SUV') and (FEE>=500000 and FEE<2000000)
order by FEE desc, A.CAR_TYPE, A.CAR_ID desc