-- 생산일자가 2022년 5월
SELECT P.PRODUCT_ID, P.PRODUCT_NAME, sum(P.PRICE*O.AMOUNT) as TOTAL_SALES from FOOD_PRODUCT P join FOOD_ORDER O on P.PRODUCT_ID=O.PRODUCT_ID
where O.PRODUCE_DATE like '2022-05%'
group by P.PRODUCT_ID
order by TOTAL_SALES desc, P.PRODUCT_ID