-- 총주문량이 3,000보다 높으면서 아이스크림의 주 성분이 과일인 아이스크림의 맛을 총주문량이 큰 순서대로
SELECT FIRST_HALF.FLAVOR from FIRST_HALF, ICECREAM_INFO
where FIRST_HALF.FLAVOR=ICECREAM_INFO.FLAVOR and FIRST_HALF.TOTAL_ORDER > 3000 and ICECREAM_INFO.INGREDIENT_TYPE='fruit_based' order by FIRST_HALF.TOTAL_ORDER desc