-- 2022년 10월
SELECT BO.TITLE, BO.BOARD_ID, RE.REPLY_ID, RE.WRITER_ID, RE.CONTENTS, date_format(RE.CREATED_DATE,'%Y-%m-%d') as CREATED_DATE from USED_GOODS_BOARD as BO 
inner join USED_GOODS_REPLY as RE on BO.BOARD_ID=RE.BOARD_ID
where BO.CREATED_DATE like '2022-10%'
order by RE.CREATED_DATE, BO.TITLE